### ISSUE TITLE
Basic snippets

### ISSUE THREAD

**Issue by mukappalambda** [kevinliao852/fastapi-snippet#4]
### Added

- FastAPI Router snippet (`frt`): Basic FastAPI router setup.
- FastAPI Get Route snippet (`frg`): FastAPI route with HTTP GET method.
- FastAPI Post Route snippet (`frp`): FastAPI route with HTTP POST method.
- FastAPI Put Route snippet (`frpu`): FastAPI route with HTTP PUT method.
- FastAPI Delete Route snippet (`frd`): FastAPI route with HTTP DELETE method.
- SQLAlchemy Model snippet (`sqlm`): SQLAlchemy model definition.
- SQL Get From Model snippet (`sqlg`): Database query function to retrieve data.
- SQL Create From Model snippet (`sqlc`): Database function to create records.
- SQL Update From Model snippet (`sqlu`): Database function to update records.
- Pydantic Model snippet (`pym`): Pydantic model definition.
- FastAPI 400 Exception snippet (`fa400`): Raise HTTP 400 exception.
- FastAPI 401 Exception snippet (`fa401`): Raise HTTP 401 exception.
- FastAPI 403 Exception snippet (`fa403`): Raise HTTP 403 exception.
- FastAPI 404 Exception snippet (`fa404`): Raise HTTP 404 exception.
- FastAPI 422 Exception snippet (`fa422`): Raise HTTP 422 exception.
- FastAPI 500 Exception snippet (`fa500`): Raise HTTP 500 exception.
- FastAPI 503 Exception snippet (`fa503`): Raise HTTP 503 exception.
- FastAPI 504 Exception snippet (`fa504`): Raise HTTP 504 exception.

**Comment by kevinliao852** [comment]
done
